### ISSUE TITLE
my_EM error: The size of tensor a (24) must match the size of tensor b (25) at non-singleton dimension 2

### ISSUE THREAD

**Issue by didadida-r** [Audio-WestlakeU/RVAE-EM#3]
Hi, 
    i try the pretrain model, but sometimes it fail with such error.
```
input: (23041,)
Traceback (most recent call last):
  File "/home/test/code/enhance/rvb/RVAE-EM/enhance.py", line 199, in <module>
    main()
  File "/home/test/code/enhance/rvb/RVAE-EM/enhance.py", line 195, in main
    inference(0, vars(args), vars(config))
  File "/home/test/code/enhance/rvb/RVAE-EM/enhance.py", line 124, in inference
    output_sptm = algo.EM(input)
  File "/home/test/code/enhance/rvb/RVAE-EM/model/my_EM.py", line 63, in EM
    ) = self.update_speech_post_func(
  File "/home/test/python_env/anaconda3/envs/rave-em/lib/python3.9/site-packages/torch/_functorch/apis.py", line 188, in wrapped
    return vmap_impl(func, in_dims, out_dims, randomness, chunk_size, *args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/rave-em/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 266, in vmap_impl
    return _flat_vmap(
  File "/home/test/python_env/anaconda3/envs/rave-em/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 38, in fn
    return f(*args, **kwargs)
  File "/home/test/python_env/anaconda3/envs/rave-em/lib/python3.9/site-packages/torch/_functorch/vmap.py", line 379, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/home/test/code/enhance/rvb/RVAE-EM/model/my_EM.py", line 122, in update_speech_post
    H_tilde = H_tilde + CTF_filter[p] * torch.diag_embed(
RuntimeError: The size of tensor a (24) must match the size of tensor b (25) at non-singleton dimension 2
```

**Comment by PengyvWANG** [comment]
Hi, can you show me your config and the .wav file?

**Comment by PengyvWANG** [comment]
Seems like you have solved it. I will close this issue and reopen it if needed.
